### ISSUE TITLE
OSError: [WinError 1455] The paging file is too small for this operation to complete.

### ISSUE THREAD

**Issue by carlosedubarreto** [wutong16/Voxurf#2]
I was getting paging too small error when executing mesh generation

Do you have an idea of what is worng and what I could do to fix it?
Thanks
Here is a part of the log
```

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\carlo\.conda\envs\voxurf\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\carlo\.conda\envs\voxurf\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\carlo\.conda\envs\voxurf\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\carlo\.conda\envs\voxurf\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\carlo\.conda\envs\voxurf\lib\runpy.py", line 288, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\carlo\.conda\envs\voxurf\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\carlo\.conda\envs\voxurf\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\AI\3d_objects\Voxurf\Voxurf-main\run.py", line 5, in <module>
    import mmcv
  File "C:\Users\carlo\.conda\envs\voxurf\lib\site-packages\mmcv\__init__.py", line 6, in <module>
    from .fileio import *
  File "C:\Users\carlo\.conda\envs\voxurf\lib\site-packages\mmcv\fileio\__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "C:\Users\carlo\.conda\envs\voxurf\lib\site-packages\mmcv\fileio\file_client.py", line 15, in <module>
    from mmcv.utils.misc import has_method
  File "C:\Users\carlo\.conda\envs\voxurf\lib\site-packages\mmcv\utils\__init__.py", line 22, in <module>
    import torch
  File "C:\Users\carlo\.conda\envs\voxurf\lib\site-packages\torch\__init__.py", line 129, in <module>
    raise err
OSError: [WinError 1455] O arquivo de paginação é muito pequeno para que esta operação seja concluída. Error loading "C:\Users\carlo\.conda\envs\voxurf\lib\site-packages\torch\lib\cudnn_adv_infer64_8.dll" or one of its dependencies.
Traceback (most recent call last):
  File "D:\AI\3d_objects\Voxurf\Voxurf-main\run.py", line 1017, in <module>
    validate_mesh(model, 512, threshold=0.0, prefix="{}final_mesh".format(prefix), world_space=True,
  File "D:\AI\3d_objects\Voxurf\Voxurf-main\run.py", line 903, in validate_mesh
    mean_d2s, mean_s2d, over_all = dtu_eval.eval(mesh_path, scene=scene, eval_dir=os.path.join(cfg.basedir, cfg.expname, 'meshes'),
  File "D:\AI\3d_objects\Voxurf\Voxurf-main\lib\dtu_eval.py", line 84, in eval
    new_pts = mp_pool.map(sample_single_tri,
  File "C:\Users\carlo\.conda\envs\voxurf\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\carlo\.conda\envs\voxurf\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\carlo\.conda\envs\voxurf\lib\multiprocessing\pool.py", line 537, in _handle_tasks
    put(task)
  File "C:\Users\carlo\.conda\envs\voxurf\lib\multiprocessing\connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\Users\carlo\.conda\envs\voxurf\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
MemoryError
sample pcd from mesh:  11%|██████▉                                                       | 1/9 [00:28<03:48, 28.55s/it]

```

**Comment by carlosedubarreto** [comment]
Executing fixNvPE sovled the issue

Found the information for the fix here:
https://github.com/ultralytics/yolov3/issues/1643#issuecomment-939545009

https://gist.github.com/cobryan05/7d1fe28dd370e110a372c4d268dcb2e5

**Comment by JamChaos** [comment]
Thank you, bro.  I have encountered all the problems you encountered and successfully resolved them through you. Thank you again！！
